-- Exercise 6-1
-- If set A = {L M N O P} and set B = {P Q R S T}, what sets are generated by the following operations?

-- A union B
-- L M N O P Q R S T

-- A union all B
-- L M N O P P Q R S 

-- A intersect B
-- P
-- A except B
-- L M N O 

-- Exercise 6-2
-- Write a compound query that finds the first and last names of all
-- actors and customers whose last name starts with L.
USE sakila;
SELECT a.first_name fname, a.last_name lname
FROM actor a
WHERE a.last_name LIKE 'L%'
UNION
SELECT c.first_name, c.last_name
FROM customer c
WHERE c.last_name LIKE 'L%'
ORDER BY lname;

-- Write a compound query that finds the id and name of all cities and
-- countries that have a name starting with an 'S', containing an 'o', and ending with an 'a'.

SELECT ci.city_id id, ci.city name
FROM city ci
WHERE ci.city LIKE 'S%o%a'
UNION
SELECT co.country_id , co.country
FROM country co
WHERE co.country LIKE 'S%o%a';

-- Write a compound query that finds the id and name of all cities and countries 
-- that have a name starting with an 'S', containing an 'o', and ending with an 
-- 'a' in descending order by city name.

SELECT ci.city_id as id, ci.city as name
FROM city ci
WHERE ci.city LIKE 'S%o%a'
UNION ALL
SELECT co.country_id as id, co.country as name
FROM country co
WHERE co.country LIKE 'S%o%a'
ORDER BY name DESC;


-- Write a compound query that finds the first_name, last_name, and title where the first_name starts 
-- with an 'M' and the film starts with 'LOVE' and the first_name, last_name, and title where the last_name 
-- starts with an 'W' and the film title starts with 'LIFE' in ascending order by the actor's last_name.

SELECT a.first_name, a.last_name, f.title
FROM actor a
JOIN film_actor fa 
	ON a.actor_id = fa.actor_id
JOIN film f
	ON fa.film_id = f.film_id
WHERE a.first_name LIKE 'M%' AND f.title LIKE 'LOVE%'
UNION ALL
SELECT a.first_name, a.last_name, f.title
FROM actor a
JOIN film_actor fa 
	ON a.actor_id = fa.actor_id
JOIN film f
	ON fa.film_id = f.film_id
WHERE last_name LIKE 'W%' AND f.title LIKE 'LIFE%'
ORDER BY last_name DESC;


-- Write a compound query that finds the distinct last_name and title where the first_name starts with an 'M' and 
-- the film starts with 'LOVE' and the last_name and title where the last_name starts with an 'W' and the film title 
-- starts with 'LIFE' in ascending order by the actor's last_name.

SELECT a.last_name, f.title
FROM actor a
JOIN film_actor fa 
	ON a.actor_id = fa.actor_id
JOIN film f
	ON fa.film_id = f.film_id
WHERE a.first_name LIKE 'M%' AND f.title LIKE 'LOVE%'
UNION
SELECT a.last_name, f.title
FROM actor a
JOIN film_actor fa 
	ON a.actor_id = fa.actor_id
JOIN film f
	ON fa.film_id = f.film_id
WHERE last_name LIKE 'W%' AND f.title LIKE 'LIFE%'
ORDER BY last_name;